package com.jackwallner.football.data

import com.jackwallner.football.model.Metric
import com.jackwallner.football.model.Player
import com.jackwallner.football.model.SeasonPhase
import com.jackwallner.football.model.StatScoutSeason
import com.jackwallner.football.model.normalizedTeamAbbreviation
import java.io.File
import java.io.InputStream
import java.time.Instant
import java.util.zip.GZIPInputStream
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.DecodeSequenceMode
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.add
import kotlinx.serialization.json.addJsonObject
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.decodeToSequence
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray

interface PlayerCaching {
    fun loadCurrentPlayers(): List<Player>
    fun loadHistoricalPlayers(): List<Player>
    fun saveCurrentPlayers(players: List<Player>)
}

/**
 * The bundled history plus the last server snapshot of the live season.
 *
 * History ships in the APK (`players-historical.json.gz`, generated by
 * `scripts/sync-android-historical.py`) and is never fetched. The live season is
 * saved only after a server response passes [PlayerSnapshotValidator], with a
 * provenance marker beside it, so nothing but server data is ever restored.
 */
class TwoTierPlayerCache(
    private val directory: File,
    private val openHistorical: () -> InputStream?,
) : PlayerCaching {
    private val currentFile = File(directory, "players-current.json")
    private val provenanceFile = File(directory, "players-current-provenance.json")

    override fun loadCurrentPlayers(): List<Player> {
        if (!hasServerProvenance()) {
            currentFile.delete()
            provenanceFile.delete()
            return emptyList()
        }
        val cached = runCatching { currentFile.inputStream().use { readPlayers(it) } }.getOrNull() ?: return emptyList()
        return if (PlayerSnapshotValidator.isCompleteCurrent(cached)) cached else emptyList()
    }

    /** History never includes the live season, so a frozen mid-season row can't overwrite the feed. */
    override fun loadHistoricalPlayers(): List<Player> {
        val stream = openHistorical() ?: return emptyList()
        val players = runCatching { GZIPInputStream(stream.buffered(1 shl 16), 1 shl 16).use { readPlayers(it) } }.getOrDefault(emptyList())
        return players.filter { (it.season ?: 0) < StatScoutSeason.current }
    }

    override fun saveCurrentPlayers(players: List<Player>) {
        val current = players.filter { (it.season ?: 0) >= StatScoutSeason.current }
        if (current.isEmpty() || !PlayerSnapshotValidator.isCompleteCurrent(current)) return
        directory.mkdirs()
        val tmp = File(directory, "players-current.json.tmp")
        tmp.outputStream().bufferedWriter().use { writer ->
            writer.write(buildJsonArray { current.forEach { add(it.toJson()) } }.toString())
        }
        if (!tmp.renameTo(currentFile)) {
            tmp.delete()
            return
        }
        // Only after the rows are down, so a failed write never leaves a marker vouching for nothing.
        provenanceFile.writeText(buildJsonObject {
            put("schema", PROVENANCE_SCHEMA)
            put("savedAt", Instant.now().toString())
        }.toString())
    }

    private fun hasServerProvenance(): Boolean {
        val text = runCatching { provenanceFile.readText() }.getOrNull() ?: return false
        val marker = runCatching { Json.parseToJsonElement(text) as? JsonObject }.getOrNull() ?: return false
        return marker["schema"]?.toString() == PROVENANCE_SCHEMA.toString()
    }

    companion object {
        const val PROVENANCE_SCHEMA = 1

        /** Streams a JSON array of players without building the whole tree in memory. */
        @OptIn(ExperimentalSerializationApi::class)
        fun readPlayers(stream: InputStream): List<Player> =
            Json.decodeToSequence(stream, JsonElement.serializer(), DecodeSequenceMode.ARRAY_WRAPPED)
                .mapNotNull { element -> (element as? JsonObject)?.let { runCatching { Player.fromJson(it) }.getOrNull() } }
                .toList()
    }
}

fun Player.toJson(): JsonObject = buildJsonObject {
    put("id", playerId)
    put("name", name)
    put("team", team)
    put("position", position)
    put("handedness", handedness)
    put("updated_at", updatedAt.toString())
    season?.let { put("season", it) }
    put("season_type", seasonPhase.raw)
    playerType?.let { put("player_type", it) }
    source?.let { put("source", it) }
    putJsonArray("metrics") { metrics.forEach { add(it.toJson()) } }
    standardStats?.let { stats ->
        putJsonArray("standard_stats") {
            stats.forEach { s -> addJsonObject { put("id", s.id); put("label", s.label); put("value", s.value) } }
        }
    }
    putJsonArray("games") {
        games.forEach { g ->
            addJsonObject {
                put("id", g.id); put("date", g.date.toString()); put("opponent", g.opponent); put("summary", g.summary)
                put("percentile_delta", g.percentileDelta); put("key_metric", g.keyMetric)
            }
        }
    }
}

private fun Metric.toJson(): JsonObject = buildJsonObject {
    put("id", id)
    put("label", label)
    put("value", value)
    put("percentile", percentile)
    put("category", category.raw)
    qualified?.let { put("qualified", it) }
    rankable?.let { put("rankable", it) }
}

object PlayerSnapshotValidator {
    private const val MINIMUM_TEAM_COUNT = 30
    private val REQUIRED_TYPES = setOf("qb", "rb", "wr", "te", "def")

    fun isCompleteHistorical(players: List<Player>): Boolean {
        val expected = (StatScoutSeason.EARLIEST until StatScoutSeason.current).toSet()
        val grouped = players.filter { it.season in expected && it.seasonPhase == SeasonPhase.REGULAR }.groupBy { it.season!! }
        if (grouped.keys != expected) return false
        return grouped.values.all { seasonPlayers ->
            val teams = seasonPlayers.map { normalizedTeamAbbreviation(it.team) }.toSet()
            val types = seasonPlayers.mapNotNull { it.playerType?.lowercase() }.toSet()
            teams.size >= MINIMUM_TEAM_COUNT && types.containsAll(REQUIRED_TYPES) && seasonPlayers.all { it.metrics.isNotEmpty() }
        }
    }

    /** Two teams and twenty players is a real opening week; the publisher checks coverage before promotion. */
    fun isCompleteCurrent(players: List<Player>): Boolean {
        val current = players.filter { it.season == StatScoutSeason.current && it.seasonPhase == SeasonPhase.REGULAR }
        val teams = current.map { normalizedTeamAbbreviation(it.team) }.toSet()
        val types = current.mapNotNull { it.playerType?.lowercase() }.toSet()
        val labels = current.flatMap { it.metrics }.map { it.label }.toSet()
        return teams.size >= 2 && current.size >= 20 && types.containsAll(REQUIRED_TYPES) &&
            labels.containsAll(setOf("EPA/Play", "EPA/Rush", "EPA/Tgt"))
    }
}
